// FORK-ONLY: 原生右键菜单(electron-context-menu)标签 i18n [feat: native-menu-i18n]
// 跟随 app 内语言设置(renderer 经 deskfox:set_context_menu_language 同步),
// 非 OS locale;缺键回退英文默认。locale 归一:zh→zh / zh-TW|zht→zht / 其余取主语言段。

export type ContextMenuLabels = Record<string, string>

const L: Record<string, ContextMenuLabels> = {
  en: {
    cut: "Cut",
    copy: "Copy",
    paste: "Paste",
    selectAll: "Select All",
    copyLink: "Copy Link",
    saveLinkAs: "Save Link As…",
    copyImage: "Copy Image",
    copyImageAddress: "Copy Image Address",
    saveImage: "Save Image",
    saveImageAs: "Save Image As…",
    copyEmail: "Copy Email Address",
    inspect: "Inspect Element",
  },
  zh: {
    cut: "剪切",
    copy: "复制",
    paste: "粘贴",
    selectAll: "全选",
    copyLink: "复制链接",
    saveLinkAs: "链接另存为…",
    copyImage: "复制图片",
    copyImageAddress: "复制图片地址",
    saveImage: "保存图片",
    saveImageAs: "图片另存为…",
    copyEmail: "复制邮箱地址",
    inspect: "检查元素",
  },
  zht: {
    cut: "剪下",
    copy: "複製",
    paste: "貼上",
    selectAll: "全選",
    copyLink: "複製連結",
    saveLinkAs: "另存連結…",
    copyImage: "複製圖片",
    copyImageAddress: "複製圖片位址",
    saveImage: "儲存圖片",
    saveImageAs: "另存圖片…",
    copyEmail: "複製電子郵件位址",
    inspect: "檢查元素",
  },
  ja: {
    cut: "切り取り",
    copy: "コピー",
    paste: "貼り付け",
    selectAll: "すべて選択",
    copyLink: "リンクをコピー",
    saveLinkAs: "リンク先を保存…",
    copyImage: "画像をコピー",
    copyImageAddress: "画像アドレスをコピー",
    saveImage: "画像を保存",
    saveImageAs: "名前を付けて画像を保存…",
    copyEmail: "メールアドレスをコピー",
    inspect: "要素を検証",
  },
  ko: {
    cut: "잘라내기",
    copy: "복사",
    paste: "붙여넣기",
    selectAll: "모두 선택",
    copyLink: "링크 복사",
    saveLinkAs: "링크 저장…",
    copyImage: "이미지 복사",
    copyImageAddress: "이미지 주소 복사",
    saveImage: "이미지 저장",
    saveImageAs: "다른 이름으로 이미지 저장…",
    copyEmail: "이메일 주소 복사",
    inspect: "요소 검사",
  },
  de: {
    cut: "Ausschneiden",
    copy: "Kopieren",
    paste: "Einfügen",
    selectAll: "Alles auswählen",
    copyLink: "Link kopieren",
    saveLinkAs: "Link speichern unter…",
    copyImage: "Bild kopieren",
    copyImageAddress: "Bildadresse kopieren",
    saveImage: "Bild speichern",
    saveImageAs: "Bild speichern unter…",
    copyEmail: "E-Mail-Adresse kopieren",
    inspect: "Element untersuchen",
  },
  es: {
    cut: "Cortar",
    copy: "Copiar",
    paste: "Pegar",
    selectAll: "Seleccionar todo",
    copyLink: "Copiar enlace",
    saveLinkAs: "Guardar enlace como…",
    copyImage: "Copiar imagen",
    copyImageAddress: "Copiar dirección de la imagen",
    saveImage: "Guardar imagen",
    saveImageAs: "Guardar imagen como…",
    copyEmail: "Copiar dirección de correo",
    inspect: "Inspeccionar elemento",
  },
  fr: {
    cut: "Couper",
    copy: "Copier",
    paste: "Coller",
    selectAll: "Tout sélectionner",
    copyLink: "Copier le lien",
    saveLinkAs: "Enregistrer le lien sous…",
    copyImage: "Copier l'image",
    copyImageAddress: "Copier l'adresse de l'image",
    saveImage: "Enregistrer l'image",
    saveImageAs: "Enregistrer l'image sous…",
    copyEmail: "Copier l'adresse e-mail",
    inspect: "Inspecter l'élément",
  },
  br: {
    cut: "Recortar",
    copy: "Copiar",
    paste: "Colar",
    selectAll: "Selecionar tudo",
    copyLink: "Copiar link",
    saveLinkAs: "Salvar link como…",
    copyImage: "Copiar imagem",
    copyImageAddress: "Copiar endereço da imagem",
    saveImage: "Salvar imagem",
    saveImageAs: "Salvar imagem como…",
    copyEmail: "Copiar endereço de e-mail",
    inspect: "Inspecionar elemento",
  },
  ru: {
    cut: "Вырезать",
    copy: "Копировать",
    paste: "Вставить",
    selectAll: "Выделить всё",
    copyLink: "Копировать ссылку",
    saveLinkAs: "Сохранить ссылку как…",
    copyImage: "Копировать изображение",
    copyImageAddress: "Копировать адрес изображения",
    saveImage: "Сохранить изображение",
    saveImageAs: "Сохранить изображение как…",
    copyEmail: "Копировать адрес эл. почты",
    inspect: "Просмотреть код элемента",
  },
  uk: {
    cut: "Вирізати",
    copy: "Копіювати",
    paste: "Вставити",
    selectAll: "Вибрати все",
    copyLink: "Копіювати посилання",
    saveLinkAs: "Зберегти посилання як…",
    copyImage: "Копіювати зображення",
    copyImageAddress: "Копіювати адресу зображення",
    saveImage: "Зберегти зображення",
    saveImageAs: "Зберегти зображення як…",
    copyEmail: "Копіювати адресу ел. пошти",
    inspect: "Дослідити елемент",
  },
  pl: {
    cut: "Wytnij",
    copy: "Kopiuj",
    paste: "Wklej",
    selectAll: "Zaznacz wszystko",
    copyLink: "Kopiuj link",
    saveLinkAs: "Zapisz link jako…",
    copyImage: "Kopiuj obraz",
    copyImageAddress: "Kopiuj adres obrazu",
    saveImage: "Zapisz obraz",
    saveImageAs: "Zapisz obraz jako…",
    copyEmail: "Kopiuj adres e-mail",
    inspect: "Zbadaj element",
  },
  tr: {
    cut: "Kes",
    copy: "Kopyala",
    paste: "Yapıştır",
    selectAll: "Tümünü seç",
    copyLink: "Bağlantıyı kopyala",
    saveLinkAs: "Bağlantıyı farklı kaydet…",
    copyImage: "Görseli kopyala",
    copyImageAddress: "Görsel adresini kopyala",
    saveImage: "Görseli kaydet",
    saveImageAs: "Görseli farklı kaydet…",
    copyEmail: "E-posta adresini kopyala",
    inspect: "Öğeyi incele",
  },
  da: {
    cut: "Klip",
    copy: "Kopiér",
    paste: "Sæt ind",
    selectAll: "Vælg alt",
    copyLink: "Kopiér link",
    saveLinkAs: "Gem link som…",
    copyImage: "Kopiér billede",
    copyImageAddress: "Kopiér billedadresse",
    saveImage: "Gem billede",
    saveImageAs: "Gem billede som…",
    copyEmail: "Kopiér e-mailadresse",
    inspect: "Undersøg element",
  },
  no: {
    cut: "Klipp ut",
    copy: "Kopier",
    paste: "Lim inn",
    selectAll: "Velg alt",
    copyLink: "Kopier lenke",
    saveLinkAs: "Lagre lenke som…",
    copyImage: "Kopier bilde",
    copyImageAddress: "Kopier bildeadresse",
    saveImage: "Lagre bilde",
    saveImageAs: "Lagre bilde som…",
    copyEmail: "Kopier e-postadresse",
    inspect: "Inspiser element",
  },
  th: {
    cut: "ตัด",
    copy: "คัดลอก",
    paste: "วาง",
    selectAll: "เลือกทั้งหมด",
    copyLink: "คัดลอกลิงก์",
    saveLinkAs: "บันทึกลิงก์เป็น…",
    copyImage: "คัดลอกรูปภาพ",
    copyImageAddress: "คัดลอกที่อยู่รูปภาพ",
    saveImage: "บันทึกรูปภาพ",
    saveImageAs: "บันทึกรูปภาพเป็น…",
    copyEmail: "คัดลอกที่อยู่อีเมล",
    inspect: "ตรวจสอบองค์ประกอบ",
  },
  ar: {
    cut: "قص",
    copy: "نسخ",
    paste: "لصق",
    selectAll: "تحديد الكل",
    copyLink: "نسخ الرابط",
    saveLinkAs: "حفظ الرابط باسم…",
    copyImage: "نسخ الصورة",
    copyImageAddress: "نسخ عنوان الصورة",
    saveImage: "حفظ الصورة",
    saveImageAs: "حفظ الصورة باسم…",
    copyEmail: "نسخ عنوان البريد الإلكتروني",
    inspect: "فحص العنصر",
  },
  bs: {
    cut: "Izreži",
    copy: "Kopiraj",
    paste: "Zalijepi",
    selectAll: "Odaberi sve",
    copyLink: "Kopiraj link",
    saveLinkAs: "Sačuvaj link kao…",
    copyImage: "Kopiraj sliku",
    copyImageAddress: "Kopiraj adresu slike",
    saveImage: "Sačuvaj sliku",
    saveImageAs: "Sačuvaj sliku kao…",
    copyEmail: "Kopiraj email adresu",
    inspect: "Ispitaj element",
  },
}

export const SUPPORTED_MENU_LOCALES = Object.keys(L)

export function normalizeMenuLocale(input: string | undefined): string {
  if (!input) return "en"
  const lower = input.toLowerCase()
  if (lower === "zht" || lower.startsWith("zh-tw") || lower.startsWith("zh-hant") || lower.startsWith("zh-hk"))
    return "zht"
  if (lower.startsWith("zh")) return "zh"
  if (lower.startsWith("pt")) return "br"
  if (lower.startsWith("nb") || lower.startsWith("nn")) return "no"
  const primary = lower.split(/[-_]/)[0]
  return primary in L ? primary : "en"
}

export function labelsFor(locale: string | undefined): ContextMenuLabels {
  return L[normalizeMenuLocale(locale)] ?? L.en
}
